# Generated by Django 5.1.5 on 2025-07-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appareil',
            name='etat',
            field=models.CharField(choices=[('fonctionnel', 'Fonctionnel'), ('en_panne', 'En panne'), ('repare', 'Réparé')], default='fonctionnel', max_length=100),
        ),
        migrations.AddField(
            model_name='intervention',
            name='situation',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminée')], default='en_cours', max_length=50),
        ),
        migrations.AddField(
            model_name='technicien',
            name='condition',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé')], default='disponible', max_length=50),
        ),
    ]
