# Generated by Django 5.1.5 on 2025-07-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0003_alter_intervention_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareil',
            name='etat',
            field=models.CharField(choices=[('en_reparation', 'En reparation'), ('en_panne', 'En panne'), ('repare', 'Réparé')], default='En reparation', max_length=100),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='situation',
            field=models.CharField(choices=[('en cours', 'En cours'), ('terminée', 'Terminée')], default='en cours', max_length=20, verbose_name='Situation'),
        ),
    ]
